In [11]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms



In [48]:
class Model:
    def __init__(self, net, cost, optimist):
        self.net = net
        self.cost = self.create_cost(cost)
        self.optimizer = self.create_optimizer(optimist)

    def create_cost(self, cost):
        support_cost = {
            'CROSS_ENTROPY': nn.CrossEntropyLoss(),
            'MSE': nn.MSELoss()
        }
        return support_cost[cost]

    def create_optimizer(self, optimist, **rests):
        support_optim = {
            'SGD': optim.SGD(self.net.parameters(), lr=0.1, **rests),
            'ADAM': optim.Adam(self.net.parameters(), lr=0.01, **rests),
            'RMSP': optim.RMSprop(self.net.parameters(), lr=0.001, **rests)
        }
        return support_optim[optimist]
    
    def train(self, train_loader, epoches=3):
        for epoch in range(epoches):
            running_loss = 0.0
            for i,data in enumerate(train_loader, 0):     # enumerate(data, start = 0) start: 索引的起始值
                inputs, labels = data
                
                self.optimizer.zero_grad()
                
                # forward + backward + optimize
                outputs = self.net(inputs)
                loss = self.cost(outputs, labels)
                loss.backward()
                self.optimizer.step()
                
                running_loss += loss.item()
                if i % 100 == 0:
                    print('[epoch %d, %.2f%%] loss: %.3f'%
                         (epoch + 1, (i + 1) * 1. / len(train_loader), running_loss / 100))
                    running_loss = 0
        print('Finishing Training.')
        
    
    def evaluate(self, test_loader):
        print('Evaluating.......')
        correct = 0
        total = 0
        with torch.no_grad():   # no grad when test and predict
            for data in test_loader:
                images, labels = data
                outputs = self.net(images)
                predicted = torch.argmax(outputs, 1)   # np.argmax(a, axis)  torch.argmax(a, dim = 1) 返回一列，按行求 
                total += labels.size(0)
                correct += (predicted == labels).sum().item()    # items() 访问位置元素值
        print('Accuracy of the network on the test images: %d %%' %
             (100 * correct / total))
        
def mnist_load_data():
    transform = transforms.Compose(
    [transforms.ToTensor(),
    transforms.Normalize([0,], [1,])])
    
    trainset = torchvision.datasets.MNIST(root='/Users/snszz/PycharmProjects/CV/第10周/代码/data', train = True,
                                         download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=32, 
                                             shuffle=True, num_workers=2)
    testset = torchvision.datasets.MNIST(root='/Users/snszz/PycharmProjects/CV/第10周/代码/data', train=False,
                                        download=True, transform=transform)
    testloader = torch.utils.data.DataLoader(testset, batch_size=32, 
                                            shuffle=True, num_workers=2)
    return trainloader, testloader

class MnistNet(torch.nn.Module):
    def __init__(self):
        super(MnistNet, self).__init__()
        self.fc1 = torch.nn.Linear(28*28, 512)
        self.fc2 = torch.nn.Linear(512, 512)
        self.fc3 = torch.nn.Linear(512, 10)
        
    def forward(self, x):
        x = x.view(-1, 28*28)  # 输入
        x = F.relu(self.fc1(x))  
        x = F.relu(self.fc2(x))
        x = F.softmax(self.fc3(x), dim=1)
        return x

# if __name__ == '__main__':
#     # train for mnist
#     net = MnistNet()
#     model = Model(net, 'CROSS_ENTROPY', 'RMSP')
#     train_loader, test_loader = mnist_load_data()
#     model.train(train_loader)
#     model.evaluate(test_loader)
    
        
                
                
                
    

In [3]:
# 对于损失函数

def create_cost(cost):
    support_cost = {
        'CROSS_ENTROPY':nn.CrossEntropyLoss(),
        'MSE':nn.MSELoss()
    }
    return support_cost[cost]


    


1 0
2 1
3 2
4 3
5 4


In [19]:
def create_optimizer(optimist):
    support_optim = {
        'SGD': optim.SGD(self.net.parameters(), lr = 0.1),
        'ADAM': optim.Adam(self.net.parameters(), lr = 0.01),
        'RMSP': optim.RMSprop(self.net.parameters(), lr=0.001)
    }
    
    return support_optim[optimist]





In [20]:
def train(train_loader, epoches=3):
    for epoch in epoches:
        running_loss = 0.0
        for i, data in enumerate(train_loader, 0):
            inputs, labels = data
            
            optim.Adam.zero_grad()
            
            # forward + backward + optimize
            
            outputs = MnistNet()
            outputs = outputs(inputs)
            loss = nn.CrossEntropyLoss()
            loss = loss(outputs, labels)
            loss.backward()
            optim.Adam.step()
            
            running_loss += loss.items()
            if i % 100 == 0:
                print('[epoch %d, %.2f%%] loss: %.3f' %
                     (epoch + 1, (i + 1) * 1. / len(train_loader),running_loss / 100))
                running_loss = 0.0
                
        print('Finishing Training')

In [29]:
class MnistNet(torch.nn.Module):
    def __init__(self):
        super(MnistNet, self).__init__()
        self.fc1 = torch.nn.Linear(3, 5)
        self.fc2 = torch.nn.Linear(5, 3)
        self.fc3 = torch.nn.Linear(3, 2)

    def forward(self, x):
        x = x.view(-1, 3)     # 输入
        x = F.relu(self.fc1(x))   # x W^T + b , 激活
        x = F.relu(self.fc2(x))
        x = F.softmax(self.fc3(x), dim=1)
        return x    

In [30]:
x = np.random.rand(4,3)
model = MnistNet()
model.state_dict()

for key, values in model.state_dict().items():
    print(key)
    print(values)

fc1.weight
tensor([[ 0.3879, -0.0392, -0.0430],
        [-0.2918, -0.5412, -0.3935],
        [ 0.2137, -0.4373, -0.2369],
        [ 0.1555,  0.1387, -0.2501],
        [-0.3234, -0.5678, -0.2867]])
fc1.bias
tensor([-0.1807,  0.5482, -0.4705,  0.2494, -0.4285])
fc2.weight
tensor([[-0.1483,  0.1804,  0.0019,  0.2590, -0.3230],
        [ 0.0648,  0.4441, -0.0987, -0.4413,  0.0536],
        [-0.4020, -0.1324, -0.2449,  0.4372,  0.2633]])
fc2.bias
tensor([-0.4097, -0.1889,  0.4468])
fc3.weight
tensor([[-0.5185,  0.3301, -0.2752],
        [-0.3802, -0.4482, -0.2355]])
fc3.bias
tensor([0.2711, 0.5086])


In [32]:
x = torch.Tensor(x)
model = model(x)
model
            
            

tensor([[0.4358, 0.5642],
        [0.4354, 0.5646],
        [0.4355, 0.5645],
        [0.4356, 0.5644]], grad_fn=<SoftmaxBackward>)

In [33]:
x.size(0)

4

In [ ]:
def evaluate(test_loader):
    print('Evaluating...')
    correct = 0
    total = 0
    
    with torch.no_grad():
        for data in test_loader:
            images, labels = data
            
            outputs = self.net(images)
            predicted = torch.argmax(outputs, 1)
            total += labels.size(0)
            correct += (predicted == outputs).sum().item()
            

In [34]:

def mnist_load_data():
    transform = transforms.Compose(
        [transforms.ToTensor(),
         transforms.Normalize([0,], [1,])])

    trainset = torchvision.datasets.MNIST(root='/Users/snszz/PycharmProjects/CV/第10周/代码/data', train=True,
                                            download=True, transform=transform)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=32,
                                              shuffle=True, num_workers=2)

    testset = torchvision.datasets.MNIST(root='/Users/snszz/PycharmProjects/CV/第10周/代码/data', train=False,
                                           download=True, transform=transform)
    testloader = torch.utils.data.DataLoader(testset, batch_size=32,shuffle=True, num_workers=2)
    return trainloader, testloader


In [35]:
trainloader, testloader = mnist_load_data()


In [46]:
# for data  in trainloader:
#     inputs, labels = data
#     print(inputs.size())
#     print(labels)


In [49]:
if __name__ == '__main__':
    # train for mnist
    net = MnistNet()
    model = Model(net, 'CROSS_ENTROPY', 'ADAM')
    train_loader, test_loader = mnist_load_data()
    model.train(train_loader)
    model.evaluate(test_loader)
    

[epoch 1, 0.00%] loss: 0.023
[epoch 1, 0.05%] loss: 2.341
[epoch 1, 0.11%] loss: 2.346
[epoch 1, 0.16%] loss: 2.346
[epoch 1, 0.21%] loss: 2.357
[epoch 1, 0.27%] loss: 2.340
[epoch 1, 0.32%] loss: 2.353
[epoch 1, 0.37%] loss: 2.350
[epoch 1, 0.43%] loss: 2.352
[epoch 1, 0.48%] loss: 2.349
[epoch 1, 0.53%] loss: 2.345
[epoch 1, 0.59%] loss: 2.359
[epoch 1, 0.64%] loss: 2.334
[epoch 1, 0.69%] loss: 2.346
[epoch 1, 0.75%] loss: 2.357
[epoch 1, 0.80%] loss: 2.348
[epoch 1, 0.85%] loss: 2.352
[epoch 1, 0.91%] loss: 2.350
[epoch 1, 0.96%] loss: 2.344
[epoch 2, 0.00%] loss: 0.024
[epoch 2, 0.05%] loss: 2.341
[epoch 2, 0.11%] loss: 2.347
[epoch 2, 0.16%] loss: 2.348
[epoch 2, 0.21%] loss: 2.350
[epoch 2, 0.27%] loss: 2.359
[epoch 2, 0.32%] loss: 2.342
[epoch 2, 0.37%] loss: 2.350
[epoch 2, 0.43%] loss: 2.350
[epoch 2, 0.48%] loss: 2.357
[epoch 2, 0.53%] loss: 2.348
[epoch 2, 0.59%] loss: 2.346
[epoch 2, 0.64%] loss: 2.343
[epoch 2, 0.69%] loss: 2.349
[epoch 2, 0.75%] loss: 2.348
[epoch 2, 0.80

In [50]:
if __name__ == '__main__':
    # train for mnist
    net = MnistNet()
    model = Model(net, 'CROSS_ENTROPY', 'SGD')
    train_loader, test_loader = mnist_load_data()
    model.train(train_loader)
    model.evaluate(test_loader)

[epoch 1, 0.00%] loss: 0.023
[epoch 1, 0.05%] loss: 2.301
[epoch 1, 0.11%] loss: 2.294
[epoch 1, 0.16%] loss: 2.265
[epoch 1, 0.21%] loss: 2.175
[epoch 1, 0.27%] loss: 2.008
[epoch 1, 0.32%] loss: 1.811
[epoch 1, 0.37%] loss: 1.730
[epoch 1, 0.43%] loss: 1.693
[epoch 1, 0.48%] loss: 1.677
[epoch 1, 0.53%] loss: 1.671
[epoch 1, 0.59%] loss: 1.655
[epoch 1, 0.64%] loss: 1.648
[epoch 1, 0.69%] loss: 1.656
[epoch 1, 0.75%] loss: 1.639
[epoch 1, 0.80%] loss: 1.647
[epoch 1, 0.85%] loss: 1.627
[epoch 1, 0.91%] loss: 1.643
[epoch 1, 0.96%] loss: 1.632
[epoch 2, 0.00%] loss: 0.017
[epoch 2, 0.05%] loss: 1.636
[epoch 2, 0.11%] loss: 1.620
[epoch 2, 0.16%] loss: 1.629
[epoch 2, 0.21%] loss: 1.620
[epoch 2, 0.27%] loss: 1.631
[epoch 2, 0.32%] loss: 1.612
[epoch 2, 0.37%] loss: 1.617
[epoch 2, 0.43%] loss: 1.623
[epoch 2, 0.48%] loss: 1.621
[epoch 2, 0.53%] loss: 1.619
[epoch 2, 0.59%] loss: 1.615
[epoch 2, 0.64%] loss: 1.618
[epoch 2, 0.69%] loss: 1.625
[epoch 2, 0.75%] loss: 1.614
[epoch 2, 0.80

In [51]:
if __name__ == '__main__':
    # train for mnist
    net = MnistNet()
    model = Model(net, 'CROSS_ENTROPY', 'RMSP')
    train_loader, test_loader = mnist_load_data()
    model.train(train_loader)
    model.evaluate(test_loader)

[epoch 1, 0.00%] loss: 0.023
[epoch 1, 0.05%] loss: 1.785
[epoch 1, 0.11%] loss: 1.589
[epoch 1, 0.16%] loss: 1.563
[epoch 1, 0.21%] loss: 1.562
[epoch 1, 0.27%] loss: 1.553
[epoch 1, 0.32%] loss: 1.542
[epoch 1, 0.37%] loss: 1.532
[epoch 1, 0.43%] loss: 1.533
[epoch 1, 0.48%] loss: 1.532
[epoch 1, 0.53%] loss: 1.526
[epoch 1, 0.59%] loss: 1.532
[epoch 1, 0.64%] loss: 1.528
[epoch 1, 0.69%] loss: 1.519
[epoch 1, 0.75%] loss: 1.526
[epoch 1, 0.80%] loss: 1.515
[epoch 1, 0.85%] loss: 1.520
[epoch 1, 0.91%] loss: 1.518
[epoch 1, 0.96%] loss: 1.515
[epoch 2, 0.00%] loss: 0.016
[epoch 2, 0.05%] loss: 1.513
[epoch 2, 0.11%] loss: 1.505
[epoch 2, 0.16%] loss: 1.511
[epoch 2, 0.21%] loss: 1.511
[epoch 2, 0.27%] loss: 1.519
[epoch 2, 0.32%] loss: 1.510
[epoch 2, 0.37%] loss: 1.511
[epoch 2, 0.43%] loss: 1.511
[epoch 2, 0.48%] loss: 1.505
[epoch 2, 0.53%] loss: 1.502
[epoch 2, 0.59%] loss: 1.504
[epoch 2, 0.64%] loss: 1.504
[epoch 2, 0.69%] loss: 1.500
[epoch 2, 0.75%] loss: 1.506
[epoch 2, 0.80