In [9]:
import torch.nn as nn
import torch

In [4]:

m = nn.Linear(3, 4)
# nn.linear(in_features, out_fatures, bias, )
'''
x.shape = (20, 3) y.shape = (20, 4)

in_features: size of each input

in_features = 3

out_features: size of each 
out_features = 4

input: math (N, *, H_{in})
'''
m.state_dict()

'''
m.state_dict().keys()
>>> odict_keys(['weight', 'bias'])

m.weight  shape (4, 3) (out, in)

m.bias  shape(4, ),  (out)

'''

OrderedDict([('weight',
              tensor([[-0.0510, -0.5515, -0.1412],
                      [ 0.1045,  0.2498,  0.2183],
                      [ 0.5471, -0.4766,  0.1368],
                      [-0.1376,  0.0251, -0.4430]])),
             ('bias', tensor([-0.2121,  0.4235,  0.4797,  0.5218]))])

In [8]:
m.bias.shape

torch.Size([4])

In [11]:
m1 = nn.Linear(20, 30)
imput = torch.randn(128, 20)
output = m1(imput)
output.size()

torch.Size([128, 30])

In [12]:
m.weight.size()

torch.Size([4, 3])

In [13]:
m.weight.shape

torch.Size([4, 3])

In [17]:
d = m.weight
d.view(-1, 4)


tensor([[-0.0510, -0.5515, -0.1412,  0.1045],
        [ 0.2498,  0.2183,  0.5471, -0.4766],
        [ 0.1368, -0.1376,  0.0251, -0.4430]], grad_fn=<ViewBackward>)

In [18]:
m.weight

Parameter containing:
tensor([[-0.0510, -0.5515, -0.1412],
        [ 0.1045,  0.2498,  0.2183],
        [ 0.5471, -0.4766,  0.1368],
        [-0.1376,  0.0251, -0.4430]], requires_grad=True)