In [11]:
import os
import tensorflow as tf
import numpy as np

In [2]:
num_classes = 10
num_examples_pre_epoch_for_train = 50000
num_examples_pre_epoch_for_test = 10000

In [3]:
class CIFAR10Record(object):  # read data
    pass

In [ ]:
# read data from cifar_10
# set a function to realize it
def read_cifar10(file_queue):
    result =CIFAR10Record()
    
    label_bytes = 1
    result.height = 32
    result.width = 32
    result.depth = 3    # RGB 三通道 所以设置为3
    
    #图片样本总元素数量
    image_bytes = result.height * result.width * result.depth
    #因为每一个样本包含图片和标签，所以最终的元素数量还需要图片样本数量加上一个标签值
    record_bytes = label_bytes + image_bytes
    #使用tf.FixedLengthRecordReader()创建一个文件读取类。该类的目的就是读取文件
    reader = tf.FixedLengthRecordReader(record_bytes=record_bytes)
    #使用该类的read()函数从文件队列里面读取文件
    result.key, value = reader.read(file_queue)
    #读取到文件以后，将读取到的文件内容从字符串形式解析为图像对应的像素数组
    record_bytes = tf.decode_raw(value, tf.uint8)
    result.label = tf.cast(tf.strided_slice(record_bytes, [0], [label_bytes]), tf.int32)
    
    

In [23]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                   [[3, 3, 3], [4, 4, 4]],
                   [[5, 5, 5], [6, 6, 6]]])

d = tf.strided_slice(t, [1,0,0], [2,1,3], [1,1,1])
with tf.Session() as sess:
    print(sess.run(d))

[[[3 3 3]]]


2021-08-23 16:42:23.417447: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA


In [25]:
# casts a tensor to a new type

x = tf.cast(d, tf.int32)
with tf.Session() as sess:
    print(sess.run(x))

[[[3 3 3]]]


In [52]:

g1 = tf.Graph()

with g1.as_default():
    tf.set_random_seed(11111)
    rn = tf.random_normal((20, ), 0 , 1, seed=1)
    d = tf.strided_slice(rn, [0],[15])
    d1 = tf.reshape(d, [3,5])
    d2 = tf.transpose(d1, [1, 0])

    with tf.Session() as sess:
        print(sess.run(rn))
    #     print('d', sess.run(d))
        print('d1 \ng',sess.run(d1))
        print('d2 \n', sess.run(d2))
    
import random
def seed_tensorflow(seed=42):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    tf.set_random_seed(seed)  
    
seed_tensorflow()
tf.set_random_seed(11111)
rn = tf.random_normal((20, ), 0 , 1, seed=1)
d = tf.strided_slice(rn, [0],[15])
d1 = tf.reshape(d, [3,5])
d2 = tf.transpose(d1, [1, 0])

with tf.Session() as sess:
    print(sess.run(rn))
#     print('d', sess.run(d))
    print('d1 \n',sess.run(d1))
    print('d2 \n', sess.run(d2))


[-0.46280667 -0.5934168   0.515147    0.4004234  -0.1310015   0.2182717
 -0.3079919   1.3443828  -1.0282623  -0.45663792  0.995802    0.12237296
 -1.0686374   0.5461912   1.9867761   0.63227123  0.10301021  1.7323191
  1.1351365   1.4918474 ]
d1 
g [[-2.682809   -1.0353603  -0.96789247 -0.33038637  1.3372775 ]
 [ 0.06058144 -0.22979157  2.06731     0.18447055 -0.932469  ]
 [ 0.10038287 -0.40800938 -0.14707929 -1.0491768   0.587055  ]]
d2 
 [[ 2.4149213   1.3852121  -0.03950839]
 [ 0.85421014 -1.2245045   2.0104637 ]
 [ 0.79108167 -0.9492664  -1.9332377 ]
 [ 0.15514271 -0.32711402 -0.02962284]
 [ 0.48522878 -0.57196707 -0.9720174 ]]
[-0.46280667 -0.5934168   0.515147    0.4004234  -0.1310015   0.2182717
 -0.3079919   1.3443828  -1.0282623  -0.45663792  0.995802    0.12237296
 -1.0686374   0.5461912   1.9867761   0.63227123  0.10301021  1.7323191
  1.1351365   1.4918474 ]
d1 
 [[-2.682809   -1.0353603  -0.96789247 -0.33038637  1.3372775 ]
 [ 0.06058144 -0.22979157  2.06731     0.18447055

In [60]:
r1 = tf.constant([[1,2,3],[4,5,6],[7,8,9]], dtype=tf.int32)
d1 = tf.strided_slice(r1, [0],[2])
d2 = tf.transpose(d1,[1,0])
with tf.Session() as sess:
    print(sess.run(r1))
    print(sess.run(d1))
    print(sess.run(d2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [57]:
tf.Tensor?

In [62]:
# 图片的增强
# 随机裁剪 tf.random_crop
r1 = tf.random_normal((3,3,3))
r2 = tf.random_crop(r1, [2, 2, 3])

with tf.Session() as sess:
    print(sess.run(r1))
    print(sess.run(r2))


[[[-0.05203531  0.01446923 -0.72729325]
  [ 0.4078864   1.4496135  -0.49595463]
  [ 0.5115382  -1.7161654  -0.18878478]]

 [[-0.6208398  -0.8725927  -0.76790595]
  [ 0.6063697  -1.8195024   0.42975593]
  [ 1.1287448  -0.18421967 -0.7366754 ]]

 [[ 0.70242524  0.21769351  0.8048375 ]
  [-0.9282432  -0.05181047 -0.61435205]
  [ 0.16932064 -0.8088874  -0.3932943 ]]]
[[[ 1.2078463   0.24665841 -0.5446295 ]
  [ 1.3327177  -0.9853704  -1.0088738 ]]

 [[ 1.1313366   0.20118745  0.39407343]
  [-0.26107475  0.20895633  0.39895642]]]


In [63]:
# tf.image.random_flip_left_right()
tf.image.random_flip_left_right()  # 左右翻转
tf.image.random_flip_up_down()     # 垂直随机翻转图像(上下颠倒)
tf.random_crop()                   #  随机地将张量裁剪到给定的大小
tf.image.random_brightness()       # 通过随机因素调整图像的亮度
tf.image.random_contrast()         # 通过随机因素调整一个或多个图像的对比度。
tf.image.adjust_gamma()            #  对输入图像执行Gamma校正。
tf.image.random_hue()              # 通过随机因素调整RGB图像的色调。
tf.image.random_jpeg_quality()     # 随机改变jpeg编码质量以诱导jpeg噪声。
tf.image.random_saturation()       # 通过随机因素调整RGB图像的饱和度。
tf.image.resize()                  #  使用指定的“方法”将“images”调整为“size”。
tf.image.resize_area()             # 使用面积插值将“图像”调整为“大小”。
tf.image.per_image_standardization() # 线性缩放“图像”有零均值和单位方差。



TypeError: random_flip_left_right() missing 1 required positional argument: 'image'

In [65]:
tf.train.shuffle_batch?