In [1]:
import numpy 
import math
import cv2
import matplotlib.pyplot as plt


In [2]:
# def convolution1(input_, filter_, strides, padding = None):
def convolution1(input_, filter_, strides = 1, padding=None):
    """
    先实现最简单的，strides = 1
    """
 
    h, w = input_.shape
    f, f = filter_.shape
    
    out_h = int((h - f) / strides) + 1   # 输出矩阵的h，w
    out_w = int((w - f) / strides) + 1
    output_ = np.zeros([out_h, out_w])  #  输出矩阵的初始化
    for i in range(0, h - f + 1):
        for j in range(0, w - f + 1):
            output_[i,j] = np.sum(input_[i:i+f, j:j+f] * filter_)
    return output_

if __name__ == '__main__':
    img = cv2.imread('lenna.png', 1)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    print(gray)
    filter_ = np.array([[1, 1, 1],[0, 0, 0],[-1, -1, -1]])
    output_ = convolution1(gray, filter_)
    print(output_)
    
    # 画图
    cv2.imshow('cov lenna', output_)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
            
        
    
    
    
    

[[162 162 162 ... 170 155 128]
 [162 162 162 ... 170 155 128]
 [162 162 162 ... 170 155 128]
 ...
 [ 43  43  50 ... 104 100  98]
 [ 44  44  55 ... 104 105 108]
 [ 44  44  55 ... 104 105 108]]
[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 ...
 [ 20.   9.  -3. ... -29. -27. -25.]
 [ -1.  -4.  -8. ... -14.  -9. -21.]
 [ -7. -10.  -9. ...  -8.  -5. -15.]]


In [15]:
def convolution2(input_, filter_, strides=1, padding=None):
    """
    先实现最简单的，strides = N
    """

    h, w = input_.shape
    f, f = filter_.shape

    out_h = int((h - f) / strides) + 1  # 输出矩阵的h，w
    out_w = int((w - f) / strides) + 1
    output_ = np.zeros([out_h, out_w])  #  输出矩阵的初始化
    for i in range(0, out_h):
        for j in range(0, out_w):
            output_[i,j] = np.sum(input_[i * strides:i * strides + f,
                                         j * strides:j * strides + f] * filter_)
            
    return output_


input_ = np.arange(64).reshape(8,8)
print(input_, 'input')
filter_ = np.array([[0, 0, 0], [0, 1, 0], [0, 0,0 ]])
output_ = convolution2(input_, filter_, strides=3, padding=None)
print(output_, 'output')

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]] input
[[ 9. 12.]
 [33. 36.]] output


In [75]:
def convolution2(input_, filter_, strides=1, padding = None):
    """
    先实现最简单的，strides = N
    padding = (f - 1) / 2
    """

    h, w = input_.shape
    f, f = filter_.shape
    if not padding:
        p = int((f - 1) / 2)
    p = padding

    out_h = int((h - f + 2 * p) / strides) + 1  # 输出矩阵的h，w
    out_w = int((w - f + 2 * p) / strides) + 1
    output_ = np.zeros([out_h, out_w])  #  输出矩阵的初始化
    # 对原始矩阵进行 padding
    zero_h = np.zeros((h, p))
    zero_w = np.zeros((p , w + 2 * p))
    input_ = np.column_stack([zero_h,input_, zero_h])
    input_ = np.row_stack([zero_w,input_, zero_w])
    print(input_, 'input_')
    for i in range(0, out_h):
        for j in range(0, out_w):
            output_[i,j] = np.sum(input_[i * strides:i * strides + f,
                                         j * strides:j * strides + f] * filter_)
            
    return output_


if __name__ == '__main__':
    img = cv2.imread('lenna.png', 1)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    print(gray)
    filter_ = np.array([[1, 1, 1],[0, 0, 0],[-1, -1, -1]])
    output_ = convolution2(gray, filter_)
    print(output_)
    
    # 画图
    cv2.imshow('cov lenna', output_)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]] input
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  2.  3.  4.  5.  6.  7.  0.  0.]
 [ 0.  0.  8.  9. 10. 11. 12. 13. 14. 15.  0.  0.]
 [ 0.  0. 16. 17. 18. 19. 20. 21. 22. 23.  0.  0.]
 [ 0.  0. 24. 25. 26. 27. 28. 29. 30. 31.  0.  0.]
 [ 0.  0. 32. 33. 34. 35. 36. 37. 38. 39.  0.  0.]
 [ 0.  0. 40. 41. 42. 43. 44. 45. 46. 47.  0.  0.]
 [ 0.  0. 48. 49. 50. 51. 52. 53. 54. 55.  0.  0.]
 [ 0.  0. 56. 57. 58. 59. 60. 61. 62. 63.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]] input_
[[ 0.  0.  0.  0.]
 [ 0. 18. 21.  0.]
 [ 0. 42. 45.  0.]
 [ 0.  0.  0.  0.]] output


In [78]:
if __name__ == '__main__':
    img = cv2.imread('lenna.png', 1)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    print(gray)
    filter_ = np.array([[1, 1, 1],[0, 0, 0],[-1, -1, -1]])
    output_ = convolution1(gray, filter_)
    print(output_)
    
    # 画图
    cv2.imshow('cov lenna', output_)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

NameError: name 'cv2' is not defined