In [1]:
import numpy as np
import math
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a.mean(axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [4]:
a.std(axis = 0)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [11]:
std = (((0 - 2.5) ** 2 + (5- 2.5) ** 2)  * 0.5)** 0.5
std

2.5

In [12]:
(0 - 2.5) / std


-1.0

In [13]:
data = np.array([[-1,2,66,-1], [-2,6,58,-1], [-3,8,45,-2], [1,9,36,1], [2,10,62,1], [3,5,83,2]])
data


array([[-1,  2, 66, -1],
       [-2,  6, 58, -1],
       [-3,  8, 45, -2],
       [ 1,  9, 36,  1],
       [ 2, 10, 62,  1],
       [ 3,  5, 83,  2]])

In [15]:
data_mean = data.mean(axis = 0)
data_std = data.std(axis = 0)
h, w = data.shape
data_center = np.zeros((h,w))   # 标准化之后的结果
for i in range(h):
    for j in range(w):
        data_center[i,j] = (data[i,j]-data_mean[j]) / data_std[j]

data_center

array([[-0.46291005, -1.73648628,  0.50972854, -0.70710678],
       [-0.9258201 , -0.24806947, -0.02216211, -0.70710678],
       [-1.38873015,  0.49613894, -0.88648441, -1.41421356],
       [ 0.46291005,  0.86824314, -1.48486139,  0.70710678],
       [ 0.9258201 ,  1.24034735,  0.24378321,  0.70710678],
       [ 1.38873015, -0.62017367,  1.63999617,  1.41421356]])

In [16]:
# 计算协方差矩阵
data_covariance = np.dot(data_center.T, data_center)
data_covariance

array([[ 6.        ,  1.03350465,  2.83150156,  5.89188304],
       [ 1.03350465,  6.        , -3.32338561,  1.31558703],
       [ 2.83150156, -3.32338561,  6.        ,  2.35064678],
       [ 5.89188304,  1.31558703,  2.35064678,  6.        ]])

In [17]:
# 使用库
import numpy as np
from sklearn.decomposition import PCA

X = np.array([[-1,2,66,-1], [-2,6,58,-1], [-3,8,45,-2], [1,9,36,1], [2,10,62,1], [3,5,83,2]])  #导入数据，维度为4
pca = PCA(n_components=2)   #降到2维
pca.fit(X)                  #训练
newX=pca.fit_transform(X)   #降维后的数据
# PCA(copy=True, n_components=2, whiten=False)
print(pca.explained_variance_ratio_)  #输出贡献率
print(newX)                  #输出降维后的数据




[0.95713353 0.03398198]
[[  7.96504337   4.12166867]
 [ -0.43650137   2.07052079]
 [-13.63653266   1.86686164]
 [-22.28361821  -2.32219188]
 [  3.47849303  -3.95193502]
 [ 24.91311585  -1.78492421]]


In [18]:
data - data_mean


array([[ -1.        ,  -4.66666667,   7.66666667,  -1.        ],
       [ -2.        ,  -0.66666667,  -0.33333333,  -1.        ],
       [ -3.        ,   1.33333333, -13.33333333,  -2.        ],
       [  1.        ,   2.33333333, -22.33333333,   1.        ],
       [  2.        ,   3.33333333,   3.66666667,   1.        ],
       [  3.        ,  -1.66666667,  24.66666667,   2.        ]])

In [20]:
import numpy as np
import math
import copy

def PCA(data, n_components):
    # 数据标准化 按列求均值
    data_mean = data.mean(axis = 0)
    data = data - data_mean
    h, w = data.shape
    data_covariance = np.dot(data.T, data)    # 协方差阵
    #计算特征值和特征向量
    eig_vals,eig_vectors = np.linalg.eig(data_covariance)
    # 对所得的特征值进行降序排列，
    ord_eig_vals = np.argsort(-eig_vals)
    # 获得排序后的特征向量
    data_components = eig_vectors[:, ord_eig_vals[:n_components]]
    return eig_vals[ord_eig_vals], data_components, np.dot(data, data_components)

if __name__ == '__main__':
    data = np.array([[-1,2,66,-1], [-2,6,58,-1], [-3,8,45,-2], [1,9,36,1], [2,10,62,1], [3,5,83,2]])  #导入数据，维度为4
    eig_vals, data_components, new_data = PCA(data, 2)
    print('排序后的特征值：\n', eig_vals)                  #输出降维后的数据
    print('排序后的特征值对应的2个特征向量：\n', data_components)
    print('新的降维后的矩阵:\n', new_data)







[[ -1.          -4.66666667   7.66666667  -1.        ]
 [ -2.          -0.66666667  -0.33333333  -1.        ]
 [ -3.           1.33333333 -13.33333333  -2.        ]
 [  1.           2.33333333 -22.33333333   1.        ]
 [  2.           3.33333333   3.66666667   1.        ]
 [  3.          -1.66666667  24.66666667   2.        ]]
排序后的特征值：
 [13.64978142  8.95250418  1.31585539  0.08185901]
排序后的特征值对应的2个特征向量：
 [[-0.64617154 -0.15597752]
 [-0.00946454 -0.783173  ]
 [-0.42900014  0.56350644]
 [-0.6311352  -0.21159291]]
新的降维后的矩阵:
 [[-27.05563179  35.99264915]
 [-23.01531727  28.50788318]
 [-16.17993775  19.98352395]
 [-16.80649276  12.87010422]
 [-28.61613256  26.58212102]
 [-38.8551196   41.96405074]]
