In [1]:
c =  1 << 2
c

4

In [2]:
r = 4 >> 2
r

# 1 >> 2 : 1往右移动2位 100

1

In [4]:
r1 = 4 >> 4
r1

0

In [5]:
for i in range(5):
    print((2 ** i) >> 1 )


0
1
2
4
8


In [7]:
n = 1
k = 2 ** (1.0 / n)
S = 4
O = 3
sigma0 = 1.2
sigma = [[(k ** s) * sigma0 * (1 << o) for s in range(S)]
         for o in range(O)]
sigma

[[1.0, 2.0, 4.0, 8.0], [2.0, 4.0, 8.0, 16.0], [4.0, 8.0, 16.0, 32.0]]

In [14]:
sigma1 = []
for o in range(O):
    temp = []
    for s in range(S):
        temp.append((k ** s) * sigma0 * (1 << o))
    sigma1.append(temp)



In [1]:
import numpy as np
c = np.array([[1,2,3],[0,1,0.5]])
print(c.mean())

1.25


In [3]:
d = 1 * 0.5 + 2 * 1 +  3 * 0
d

2.5

In [5]:
np.convolve([1,2,3], [0, 1, 0.5]) # default ‘mode = full’
'''
[3,2,1]

[1]
[0,1,0.5]

[2,1]
[0,1,0.5]

[3,2,1]
[0,1,0.5]

[3,2,1]
[0,1,0.5]

   [3,2,  1]
[0,1,0.5]

      [3,2,1]
[0,1,0.5]
'''


array([0. , 1. , 2.5, 4. , 1.5])

array([ 4,  7, 23, 35, 15])

array([ 4,  7, 23, 35])

In [13]:
np.convolve?
