In [1]:
import numpy as np
import scipy.special as ss

In [3]:
print(ss.cbrt(3))  # 立方根

1.4422495703074083


In [4]:
ss.exp10(3)  # 10 ^3

1000.0

In [5]:
ss.sindg(90) #正弦函数，参数为角度

1.0

In [6]:
ss.round(3.1) #四舍五入函数

3.0

In [7]:
S = ss
print(S.round(3.5))
print(S.round(3.499))
print(S.comb(5,3))#从5个中任选3个的组合数
print(S.perm(5,3))#排列数
print(S.gamma(4))#gamma函数
print(S.beta(10,200))#beta函数
print(S.sinc(0))#sinc函数




4.0
3.0
10.0
60.0
6.0
2.839607777781333e-18
1.0


In [8]:
# https://docs.scipy.org/doc/scipy/reference/tutorial/special.html
# scipy.special
#scipy的special模块包含了大量函数库，包括基本数学函数、特殊函数以及numpy中的所有函数
# scipy.integrate
# scipy.optimize
# scipy.fft
# scipy.signal
# scipy.linalg
# scipy.sparse.csgrapg
# scipy.spatial
# scipy.stats
# scipy.ndimage
# scipy.io


In [9]:
help(ss)

Help on package scipy.special in scipy:

NAME
    scipy.special

DESCRIPTION
    Special functions (:mod:`scipy.special`)
    
    .. currentmodule:: scipy.special
    
    Nearly all of the functions below are universal functions and follow
    broadcasting and automatic array-looping rules.
    
    .. seealso::
    
       `scipy.special.cython_special` -- Typed Cython versions of special functions
    
    
    Error handling
    
    Errors are handled by returning NaNs or other appropriate values.
    Some of the special function routines can emit warnings or raise
    exceptions when an error occurs. By default this is disabled; to
    query and control the current error handling state the following
    functions are provided.
    
    .. autosummary::
       :toctree: generated/
    
       geterr                 -- Get the current way of handling special-function errors.
       seterr                 -- Set how special-function errors are handled.
       errstate              

In [10]:
c = np.array([1,2,3])
d = ss.expit(c)
d


array([0.73105858, 0.88079708, 0.95257413])

In [11]:
e = ss.softmax(c)
e


array([0.09003057, 0.24472847, 0.66524096])

In [13]:
1 / (1 + np.exp(-c))

array([0.73105858, 0.88079708, 0.95257413])

In [14]:
f = lambda x: ss.expit(x)
f(c)


array([0.73105858, 0.88079708, 0.95257413])

In [16]:
1760 - 10

1750

In [17]:
28 * 28

784

In [20]:
784 * 2 + 20

1588

In [21]:
data_file = open('/Users/snszz/PycharmProjects/CV/第九周/代码/NeuralNetWork_从零开始/dataset/mnist_test.csv')
data_list = data_file.readlines()
data_file.close()
print('len(data_list): ', len(data_list))
# print('data_list[0]: ',data_list[0])
print(len(data_list[0]))



len(data_list):  10
1760


In [71]:
# numpy 复习
# https://blog.csdn.net/lwplwf/article/details/55506896
data_ = data_list[1]


In [72]:
a3d = np.zeros((2,3,4))
a5d = np.array(a3d, ndmin = 5)
print(a3d.shape)
a5d.shape
# (1, 1, 2, 3, 4) #actual shape
# (2, 3, 4, 1, 1) #desired shape


(2, 3, 4)


(1, 1, 2, 3, 4)

In [37]:
np.sqrt(1760 - 1)

41 * 41

1681

In [73]:
import cv2
image = data_.split(',')
image = np.asfarray(image[1:])
image

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0., 116., 125., 171., 255., 255.,
       150.,  93.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
       169., 253., 253., 253., 253., 253., 253., 218.,  30.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0., 169., 253., 25

In [86]:
image.shape
image = cv2.resize(image, (28, 28))
image.astype(np.uint8)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
        255, 255],
       [253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253,
        253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253,
        253, 253],
       [159, 159, 159, 159, 159, 159, 159, 159, 159, 159, 159, 159, 159,
        159, 159, 159, 159, 159, 159, 159, 159, 159, 159, 159, 159, 159,
        159, 159],
       [  

In [ ]:
import matplotlib.pyplot as plt

cv2.imshow('image', image)
cv2.waitKey(0)


In [2]:
all_values = data_list[0].split(',')
onodes = 10
targets = np.zeros(onodes) + 0.01
targets[int(all_values[0])] = 0.99
targets


NameError: name 'data_list' is not defined